# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI Test e2e

on:
  pull_request:
    branches: ["develop"]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      rabbitmq:
        image: rabbitmq:3.8
        env:
          RABBITMQ_DEFAULT_USER: guest
          RABBITMQ_DEFAULT_PASS: guest
        ports:
          - 5672

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Start Redis
        uses: supercharge/redis-github-action@1.4.0

      - name: Run chmod to make gradlew executable
        run: chmod +x ./gradlew

      - name: Test with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: |
            test
            -i
        env:
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
          SECRET: ${{ secrets.SECRET }}
          TWITTER_CLIENT_ID: ${{ secrets.TWITTER_CLIENT_ID }}
          TWITTER_CLIENT_SECRET: ${{ secrets.TWITTER_CLIENT_SECRET }}
          FRONTEND_URL: ${{ secrets.FRONTEND_URL }}
          FRONTEND_ORIGIN: ${{ secrets.FRONTEND_ORIGIN }}
          MAIN_SERVER_URL: ${{ secrets.MAIN_SERVER_URL }}
          S3_URL: ${{ secrets.S3_URL }}
          REDIS_HOST: 127.0.0.1
          MQ_HOST: localhost,
          MQ_PORT: 5672,
          MQ_USER: guest,
          MQ_PW: guest
